[project]
name = "Tree-Planting-Proof-NFT"
description = "NFT-based tree planting proofs with verifications, adoptions, carbon offset; plus independent leaderboard."
authors = ["chongdahdavid9"]
telemetry = false

[contracts.charity-donation-tracker]
path = "contracts/charity-donation-tracker.clar"
clarity_version = 1
